package com.ysu.graduationproject.po;

import java.util.Date;

public class Basedetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedetail.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String tableid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedetail.bloodSuger
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private Double bloodsuger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedetail.bloodSugerType
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String bloodsugertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedetail.bloodPressure
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private Double bloodpressureHeigh;

    private Double bloodpressureLow;

    private String bloodPressLevel;

    private String bloodSugerLevel;

    private String weightLevel;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedetail.weight
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedetail.createTime
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private Date createtime;

    private String createtimeS;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedetail.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedetail.detailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String detailsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedetail.tableId
     *
     * @return the value of basedetail.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedetail.tableId
     *
     * @param tableid the value for basedetail.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setTableid(String tableid) {
        this.tableid = tableid == null ? null : tableid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedetail.bloodSuger
     *
     * @return the value of basedetail.bloodSuger
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public Double getBloodsuger() {
        return bloodsuger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedetail.bloodSuger
     *
     * @param bloodsuger the value for basedetail.bloodSuger
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setBloodsuger(Double bloodsuger) {
        this.bloodsuger = bloodsuger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedetail.bloodSugerType
     *
     * @return the value of basedetail.bloodSugerType
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getBloodsugertype() {
        return bloodsugertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedetail.bloodSugerType
     *
     * @param bloodsugertype the value for basedetail.bloodSugerType
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setBloodsugertype(String bloodsugertype) {
        this.bloodsugertype = bloodsugertype == null ? null : bloodsugertype.trim();
    }

    public Double getBloodpressureHeigh() {
        return bloodpressureHeigh;
    }

    public void setBloodpressureHeigh(Double bloodpressureHeigh) {
        this.bloodpressureHeigh = bloodpressureHeigh;
    }

    public Double getBloodpressureLow() {
        return bloodpressureLow;
    }

    public void setBloodpressureLow(Double bloodpressureLow) {
        this.bloodpressureLow = bloodpressureLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedetail.weight
     *
     * @return the value of basedetail.weight
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedetail.weight
     *
     * @param weight the value for basedetail.weight
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedetail.createTime
     *
     * @return the value of basedetail.createTime
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedetail.createTime
     *
     * @param createtime the value for basedetail.createTime
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedetail.delFlag
     *
     * @return the value of basedetail.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedetail.delFlag
     *
     * @param delflag the value for basedetail.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedetail.detailsId
     *
     * @return the value of basedetail.detailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getDetailsid() {
        return detailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedetail.detailsId
     *
     * @param detailsid the value for basedetail.detailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setDetailsid(String detailsid) {
        this.detailsid = detailsid == null ? null : detailsid.trim();
    }


    public String getBloodPressLevel() {
        return bloodPressLevel;
    }

    public void setBloodPressLevel(String bloodPressLevel) {
        this.bloodPressLevel = bloodPressLevel;
    }

    public String getBloodSugerLevel() {
        return bloodSugerLevel;
    }

    public void setBloodSugerLevel(String bloodSugerLevel) {
        this.bloodSugerLevel = bloodSugerLevel;
    }

    public String getWeightLevel() {
        return weightLevel;
    }

    public void setWeightLevel(String weightLevel) {
        this.weightLevel = weightLevel;
    }

    public String getCreatetimeS() {
        return createtimeS;
    }

    public void setCreatetimeS(String createtimeS) {
        this.createtimeS = createtimeS;
    }
}