package com.ysu.graduationproject.po;

public class Details {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String tableid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.caseId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String caseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.baseDetailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String basedetailsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.otherDetailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String otherdetailsid;

    //临界高压
    private Double criticalBloodPressureHeigh;

    //临界低压
    private Double criticalBloodPressureLow;

    //临界空腹血糖
    private Double criticalFastingBloodSuger;

    //临界餐后血糖
    private Double criticalPostprandialBloodSuger;

    //临界体重
    private Double criticalWeight;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.tableId
     *
     * @return the value of details.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.tableId
     *
     * @param tableid the value for details.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setTableid(String tableid) {
        this.tableid = tableid == null ? null : tableid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.caseId
     *
     * @return the value of details.caseId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getCaseid() {
        return caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.caseId
     *
     * @param caseid the value for details.caseId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setCaseid(String caseid) {
        this.caseid = caseid == null ? null : caseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.baseDetailsId
     *
     * @return the value of details.baseDetailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getBasedetailsid() {
        return basedetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.baseDetailsId
     *
     * @param basedetailsid the value for details.baseDetailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setBasedetailsid(String basedetailsid) {
        this.basedetailsid = basedetailsid == null ? null : basedetailsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.otherDetailsId
     *
     * @return the value of details.otherDetailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getOtherdetailsid() {
        return otherdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.otherDetailsId
     *
     * @param otherdetailsid the value for details.otherDetailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setOtherdetailsid(String otherdetailsid) {
        this.otherdetailsid = otherdetailsid == null ? null : otherdetailsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.delFlag
     *
     * @return the value of details.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.delFlag
     *
     * @param delflag the value for details.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }

    public Double getCriticalFastingBloodSuger() {
        return criticalFastingBloodSuger;
    }

    public void setCriticalFastingBloodSuger(Double criticalFastingBloodSuger) {
        this.criticalFastingBloodSuger = criticalFastingBloodSuger;
    }

    public Double getCriticalPostprandialBloodSuger() {
        return criticalPostprandialBloodSuger;
    }

    public void setCriticalPostprandialBloodSuger(Double criticalPostprandialBloodSuger) {
        this.criticalPostprandialBloodSuger = criticalPostprandialBloodSuger;
    }

    public Double getCriticalWeight() {
        return criticalWeight;
    }

    public void setCriticalWeight(Double criticalWeight) {
        this.criticalWeight = criticalWeight;
    }

    public Double getCriticalBloodPressureHeigh() {
        return criticalBloodPressureHeigh;
    }

    public void setCriticalBloodPressureHeigh(Double criticalBloodPressureHeigh) {
        this.criticalBloodPressureHeigh = criticalBloodPressureHeigh;
    }

    public Double getCriticalBloodPressureLow() {
        return criticalBloodPressureLow;
    }

    public void setCriticalBloodPressureLow(Double criticalBloodPressureLow) {
        this.criticalBloodPressureLow = criticalBloodPressureLow;
    }

    @Override
    public String toString() {
        return "Details{" +
                "tableid='" + tableid + '\'' +
                ", caseid='" + caseid + '\'' +
                ", basedetailsid='" + basedetailsid + '\'' +
                ", otherdetailsid='" + otherdetailsid + '\'' +
                ", criticalBloodPressureHeigh=" + criticalBloodPressureHeigh +
                ", criticalBloodPressureLow=" + criticalBloodPressureLow +
                ", criticalFastingBloodSuger=" + criticalFastingBloodSuger +
                ", criticalPostprandialBloodSuger=" + criticalPostprandialBloodSuger +
                ", criticalWeight=" + criticalWeight +
                ", delflag='" + delflag + '\'' +
                '}';
    }
}