package com.ysu.graduationproject.po;

import java.util.Date;

public class Doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String tableid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.name
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.phone
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.birthday
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private Date birthday;

    private String birthdayS;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.numb
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private Integer numb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.password
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String password;

    private String email;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getBirthdayS() {
        return birthdayS;
    }

    public void setBirthdayS(String birthdayS) {
        this.birthdayS = birthdayS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.tableId
     *
     * @return the value of doctor.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.tableId
     *
     * @param tableid the value for doctor.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setTableid(String tableid) {
        this.tableid = tableid == null ? null : tableid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.name
     *
     * @return the value of doctor.name
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.name
     *
     * @param name the value for doctor.name
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.phone
     *
     * @return the value of doctor.phone
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.phone
     *
     * @param phone the value for doctor.phone
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.birthday
     *
     * @return the value of doctor.birthday
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.birthday
     *
     * @param birthday the value for doctor.birthday
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.numb
     *
     * @return the value of doctor.numb
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public Integer getNumb() {
        return numb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.numb
     *
     * @param numb the value for doctor.numb
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setNumb(Integer numb) {
        this.numb = numb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.delFlag
     *
     * @return the value of doctor.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.delFlag
     *
     * @param delflag the value for doctor.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.password
     *
     * @return the value of doctor.password
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.password
     *
     * @param password the value for doctor.password
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}