package com.ysu.graduationproject.po;

import java.util.Date;

public class Moredetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moredetails.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String tableid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moredetails.glycosylatedRedProtein
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String glycosylatedredprotein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moredetails.heart
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String heart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moredetails.footBottom
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String footbottom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moredetails.eyes
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String eyes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moredetails.urineProtein
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String urineprotein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moredetails.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moredetails.detailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String detailsid;

    private Date createTime;

    public Date getCreatetime() {
        return createTime;
    }

    public void setCreatetime(Date createtime) {
        this.createTime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moredetails.tableId
     *
     * @return the value of moredetails.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moredetails.tableId
     *
     * @param tableid the value for moredetails.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setTableid(String tableid) {
        this.tableid = tableid == null ? null : tableid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moredetails.glycosylatedRedProtein
     *
     * @return the value of moredetails.glycosylatedRedProtein
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getGlycosylatedredprotein() {
        return glycosylatedredprotein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moredetails.glycosylatedRedProtein
     *
     * @param glycosylatedredprotein the value for moredetails.glycosylatedRedProtein
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setGlycosylatedredprotein(String glycosylatedredprotein) {
        this.glycosylatedredprotein = glycosylatedredprotein == null ? null : glycosylatedredprotein.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moredetails.heart
     *
     * @return the value of moredetails.heart
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getHeart() {
        return heart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moredetails.heart
     *
     * @param heart the value for moredetails.heart
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setHeart(String heart) {
        this.heart = heart == null ? null : heart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moredetails.footBottom
     *
     * @return the value of moredetails.footBottom
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getFootbottom() {
        return footbottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moredetails.footBottom
     *
     * @param footbottom the value for moredetails.footBottom
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setFootbottom(String footbottom) {
        this.footbottom = footbottom == null ? null : footbottom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moredetails.eyes
     *
     * @return the value of moredetails.eyes
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getEyes() {
        return eyes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moredetails.eyes
     *
     * @param eyes the value for moredetails.eyes
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setEyes(String eyes) {
        this.eyes = eyes == null ? null : eyes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moredetails.urineProtein
     *
     * @return the value of moredetails.urineProtein
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getUrineprotein() {
        return urineprotein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moredetails.urineProtein
     *
     * @param urineprotein the value for moredetails.urineProtein
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setUrineprotein(String urineprotein) {
        this.urineprotein = urineprotein == null ? null : urineprotein.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moredetails.delFlag
     *
     * @return the value of moredetails.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moredetails.delFlag
     *
     * @param delflag the value for moredetails.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moredetails.detailsId
     *
     * @return the value of moredetails.detailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getDetailsid() {
        return detailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moredetails.detailsId
     *
     * @param detailsid the value for moredetails.detailsId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setDetailsid(String detailsid) {
        this.detailsid = detailsid == null ? null : detailsid.trim();
    }
}