package com.ysu.graduationproject.po;

public class PatientKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String tableid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.phone
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.tableId
     *
     * @return the value of patient.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.tableId
     *
     * @param tableid the value for patient.tableId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setTableid(String tableid) {
        this.tableid = tableid == null ? null : tableid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.phone
     *
     * @return the value of patient.phone
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.phone
     *
     * @param phone the value for patient.phone
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}