package com.ysu.graduationproject.po;

import java.util.Date;

public class Patient extends PatientKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.doctorId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String doctorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.caseId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String patientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.name
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.birthday
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private Date birthday;

    private String birthdayS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.password
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    private String password;

    private String email;

    //是否置顶
    private String upset;

    //最近一次日常数据记录
    private Basedetail basedetail;

    public Basedetail getBasedetail() {
        return basedetail;
    }

    public void setBasedetail(Basedetail basedetail) {
        this.basedetail = basedetail;
    }

    public String getUpset() {
        return upset;
    }

    public void setUpset(String upset) {
        this.upset = upset;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.doctorId
     *
     * @return the value of patient.doctorId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.doctorId
     *
     * @param doctorid the value for patient.doctorId
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setDoctorid(String doctorid) {
        this.doctorid = doctorid == null ? null : doctorid.trim();
    }

    public String getPatientType() {
        return patientType;
    }

    public void setPatientType(String patientType) {
        this.patientType = patientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.name
     *
     * @return the value of patient.name
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.name
     *
     * @param name the value for patient.name
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.birthday
     *
     * @return the value of patient.birthday
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.birthday
     *
     * @param birthday the value for patient.birthday
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.delFlag
     *
     * @return the value of patient.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.delFlag
     *
     * @param delflag the value for patient.delFlag
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.password
     *
     * @return the value of patient.password
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.password
     *
     * @param password the value for patient.password
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public String getBirthdayS() {
        return birthdayS;
    }

    public void setBirthdayS(String birthdayS) {
        this.birthdayS = birthdayS;
    }
}