package com.ysu.graduationproject.dao;

import com.ysu.graduationproject.common.ServerResponse;
import com.ysu.graduationproject.po.Details;
import com.ysu.graduationproject.po.Doctor;

import java.util.List;

public interface DetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int deleteByPrimaryKey(String tableid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int insert(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int insertSelective(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    Details selectByPrimaryKey(String tableid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int updateByPrimaryKeySelective(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int updateByPrimaryKey(Details record);

    Details selectAllDetailsId(String patientId);
}