package com.ysu.graduationproject.dao;

import com.ysu.graduationproject.po.Moredetails;

import java.util.List;

public interface MoredetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moredetails
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int deleteByPrimaryKey(String tableid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moredetails
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int insert(Moredetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moredetails
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int insertSelective(Moredetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moredetails
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    Moredetails selectByPrimaryKey(String tableid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moredetails
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int updateByPrimaryKeySelective(Moredetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moredetails
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int updateByPrimaryKey(Moredetails record);

    List<Moredetails> selectByDetailsId(String detailsid);
}