package com.ysu.graduationproject.dao;

import com.ysu.graduationproject.common.ServerResponse;
import com.ysu.graduationproject.po.Patient;
import com.ysu.graduationproject.po.PatientKey;

import java.util.List;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int deleteByPrimaryKey(PatientKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int insertSelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    Patient selectByPrimaryKey(String tableid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int updateByPrimaryKeySelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbg.generated Tue Apr 07 13:18:01 CST 2020
     */
    int updateByPrimaryKey(Patient record);

    Patient selectByPhone(String phone);

    Patient selectByPhoneAndPassword(Patient patient);

    List<Patient> selectPatientByDoctorId(String doctorId);

    Patient findPatientId(String detailsId);
}